import React from 'react';
import { T } from '../tokens';
import Icon from './Icon';
import { UrlyIcon } from './Squircle';

export default function Sidebar({ active, counts = {}, tagCounts = {}, settings, onNavigate, onOpenSettings }) {
  const showRecent = settings?.sidebar?.recentlyAdded !== false;
  const showFav = settings?.sidebar?.favorites !== false;
  const showTags = settings?.sidebar?.tags !== false;
  const tagNames = Object.keys(tagCounts).sort();

  return (
    <div style={{
      width: 220, flexShrink: 0,
      background: T.sidebarBg,
      backdropFilter: 'blur(30px) saturate(180%)',
      WebkitBackdropFilter: 'blur(30px) saturate(180%)',
      borderRight: `0.5px solid ${T.sep}`,
      display: 'flex', flexDirection: 'column',
      minHeight: 0,
      WebkitAppRegion: 'drag',
    }}>
      <div style={{ height: 52, padding: '0 16px', display: 'flex', alignItems: 'center', flexShrink: 0 }} />
      <div style={{ flex: 1, overflowY: 'auto', padding: '0 0 8px', WebkitAppRegion: 'no-drag' }}>
        <GroupLabel>Library</GroupLabel>
        <Item icon="apps" label="All Apps" count={counts.all ?? 0}
          selected={active === 'all'} onClick={() => onNavigate?.({ section: 'all' })} />
        {showRecent && (
          <Item icon="sparkles" label="Recently Added" count={counts.recent ?? 0}
            selected={active === 'recent'} onClick={() => onNavigate?.({ section: 'recent' })} />
        )}
        {showFav && (
          <Item icon="star" label="Favorites" count={counts.fav ?? 0}
            selected={active === 'fav'} onClick={() => onNavigate?.({ section: 'fav' })} />
        )}

        {showTags && tagNames.length > 0 && (
          <>
            <GroupLabel>Tags</GroupLabel>
            {tagNames.map(tag => (
              <Item key={tag} icon="folder" label={tag} count={tagCounts[tag]}
                selected={active === `tag:${tag}`}
                onClick={() => onNavigate?.({ section: `tag:${tag}` })} />
            ))}
          </>
        )}
      </div>

      <div style={{
        flexShrink: 0, padding: '8px 10px',
        borderTop: `0.5px solid ${T.sep}`,
        WebkitAppRegion: 'no-drag',
        display: 'flex', alignItems: 'center', gap: 8,
      }}>
        <UrlyIcon size={24} />
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: T.text }}>Urly</div>
          <div style={{ fontSize: 10.5, color: T.textTertiary }}>v1.0</div>
        </div>
        <div
          onClick={onOpenSettings}
          title="Settings (⌘,)"
          style={{
            width: 24, height: 24, display: 'flex', alignItems: 'center', justifyContent: 'center',
            borderRadius: 5, color: T.textSecondary, cursor: 'default',
          }}
          onMouseEnter={e => e.currentTarget.style.background = T.controlTrack}
          onMouseLeave={e => e.currentTarget.style.background = 'transparent'}
        >
          <SettingsGear />
        </div>
      </div>
    </div>
  );
}

function SettingsGear() {
  // 8 evenly-spaced trapezoidal teeth, generated by polar math so the shape is
  // symmetric across both axes. Inner concentric circle gives the gear its
  // recognizable hub.
  const d = "M 6.63 1.54 L 9.37 1.54 L 8.91 3.08 L 10.83 3.88 L 11.59 2.46 L 13.54 4.41 L 12.12 5.17 L 12.92 7.09 L 14.46 6.63 L 14.46 9.37 L 12.92 8.91 L 12.12 10.83 L 13.54 11.59 L 11.59 13.54 L 10.83 12.12 L 8.91 12.92 L 9.37 14.46 L 6.63 14.46 L 7.09 12.92 L 5.17 12.12 L 4.41 13.54 L 2.46 11.59 L 3.88 10.83 L 3.08 8.91 L 1.54 9.37 L 1.54 6.63 L 3.08 7.09 L 3.88 5.17 L 2.46 4.41 L 4.41 2.46 L 5.17 3.88 L 7.09 3.08 Z";
  return (
    <svg width={15} height={15} viewBox="0 0 16 16" fill="none" stroke="currentColor"
      strokeWidth={1.2} strokeLinejoin="round">
      <path d={d} />
      <circle cx="8" cy="8" r="2.3" />
    </svg>
  );
}

function GroupLabel({ children }) {
  return (
    <div style={{
      fontSize: 11, fontWeight: 600, letterSpacing: 0.2,
      color: T.textTertiary,
      padding: '14px 16px 4px',
    }}>{children}</div>
  );
}

function Item({ icon, label, count, selected, onClick }) {
  return (
    <div onClick={onClick} style={{
      display: 'flex', alignItems: 'center', gap: 8,
      height: 28, margin: '1px 8px', padding: '0 8px',
      borderRadius: 6,
      background: selected ? T.accent : 'transparent',
      color: selected ? '#fff' : T.text,
      fontSize: 13, fontWeight: 500,
      cursor: 'default',
    }}>
      {icon && (
        <span style={{ display: 'flex', color: selected ? 'rgba(255,255,255,0.95)' : T.textSecondary }}>
          <Icon name={icon} size={15} strokeWidth={1.6} />
        </span>
      )}
      <span style={{ flex: 1, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{label}</span>
      {count != null && (
        <span style={{
          fontSize: 12, fontWeight: 500,
          color: selected ? 'rgba(255,255,255,0.78)' : T.textTertiary,
          fontVariantNumeric: 'tabular-nums',
        }}>{count}</span>
      )}
    </div>
  );
}
